[google]
title = "Google"
url = "https://google.com"
keywords = [ "google", "search" ]

[duckduckgo]
title = "DuckDuckGo"
url = "https://duckduckgo.com"
keywords = [ "duckduckgo", "search"]

[github]
title = "GitHub"
url = "https://github.com"
keywords = [ "github", "code" ]

[development]
title = "Development Tools"

[development.nix-packages]
title = "Nix Packages"
url = "https://search.nixos.org/packages"
keywords = [ "nix", "nixpkgs", "packages" ]

[development.nixos-options]
title = "NixOS Options"
url = "https://search.nixos.org/options"
keywords = [ "nix", "nixos", "nixpkgs", "packages" ]
